name: Get Kubernetes nodes
  hosts: localhost
  tasks:
    name: Get Kubernetes nodes
      set_fact:
        nodes: "{{ lookup('k8s', api_version='v1', kind='node', namespace='dev') }}"
      debug:
        msg: "The {{ nodes }} are here"
    name: Add host to inventory
      add_host:
        hostname: "{{ item }}"
        groups:
        Nodes
      with_list: "{{ nodes | json_query('[*].status.addresses[0].address') }}"
